version: "3.7"

services:
  cockroachdb:
    image: cockroachdb/cockroach:v19.1.3
    command: start --insecure
    volumes:
      - ./cockroach-data/roach:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"
  db-init:
    image: cockroachdb/cockroach:v19.1.3
    entrypoint: "/bin/bash"
    volumes:
      - ./db.dump.sql:/db.dump.sql
      - ./init.sh:/init.sh
    command: /init.sh
    depends_on:
      - cockroachdb
